/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test

import scala.None
import scala.Option

// Thanks to Gabriele for suggesting this approach
@Suppress("UNCHECKED_CAST")
fun<T> NoneFun() = Option.apply(null) as Option<T>

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun foo(x: Option<String>) {
    println(x.toString())
}

fun main() {
    println(App().greeting)
    @Suppress("UNCHECKED_CAST")
    foo(scala.`None$`.`MODULE$` as Option<String>)
    foo(NoneFun<String>())
}
