/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test

import scala.None
import scala.Option

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun foo(x: Option<String>) {}

fun main() {
    println(App().greeting)
    foo(None)
    foo(None())
}
